### ISSUE TITLE
Remove the number from task name

### ISSUE THREAD

**Issue by marcindata** [datacamp/projects-discovery-of-handwashing-python#13]
We should clean numbers from task titles.
It should not contain a number as a prefix.

Some of the projects do not contain the numbers:
https://www.datacamp.com/projects/12
It should be same for all.

As a reference, I have added the issue from the main app: datacamp/main-app#3507.

**Comment by rasmusab** [comment]
We need the task number to appear in the students Jupyter notebook. The only way to do it currently is to manually insert them.

![image](https://user-images.githubusercontent.com/1006144/33259997-e3a0ca40-d35e-11e7-8419-0d3c1a4444bd.png)

**Comment by marcindata** [comment]
@rasmusab @filipsch @rv2e - if that is the only way. 
I think we have two options:
- clean the data in projects-api project - I think should be preferred as it require to clean the data once for all projects-api consumers
- clean the data in the main-app just before we display. This approach is less flexible and each consumer of projects-api would have to clean it up.

Maybe there is another option - let me know WDYT guys?

**Comment by rv2e** [comment]
This could be done automatically on the Projects-api since we have the task number indeed.
@marcindata It's not something we will do immediately. I want to be sure we find a better way to update live project before. So if it's urgent for you, I would do a small regex that removes the number in front before.

**Comment by rv2e** [comment]
https://github.com/datacamp/projects-api/issues/131

**Comment by filipsch** [comment]
> We need the tasks number to appear in the students Jupyter notebook. The only way to do it currently is to manually insert them. (@rasmusab)

> We should clean numbers from task titles. It should not contain a number as a prefix. (@marcindata)

Have both these these statements been checked off with @martijnsublime? For me, this all feels like a lot of back and forth between a lot of different teams for a tiny enhancement. I would be surprised if our users even noticed.

If both requests are legit, I would say the following:
- Task titles have to have manually specified by the project author, as `X. project title`.
- Teach parses the title as `X. project title`, LE stores the title as `X. project title`.
- GE can remove the number with a regex if they don't want it. Has already been done, AFAIK.
- That's the end of it. LE doesn't have to do anything. TE doesn't have to do anything.

cc @mcls

**Comment by rasmusab** [comment]
> Have both these these statements been checked off with @martijnsublime?

So we discussed this on Slack at some point, but I don't remember if it was with Ramnath or Martijn. Since the tasks are numbered in the sidebar, it's nice to see which task corresponds to each code cell in the notebook by number. And the quick way of making sure that was the case was just to manually number the titles in the `project.ipynb`.

**Comment by martijnsublime** [comment]
The solution by @filipsch sounds good and easy.

**Comment by rv2e** [comment]
Perfect. @marcindata I'll close this issue and let you handle the regex on the main side then ;)
